// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBfTd6E0FGKTRC2LS5IOPA0SRxQcAh1Iw',
    appId: '1:593099494761:web:e582da5ba94d74736d19f8',
    messagingSenderId: '593099494761',
    projectId: 'emir-s-firebase-example',
    authDomain: 'emir-s-firebase-example.firebaseapp.com',
    storageBucket: 'emir-s-firebase-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfWH2w5dGTOrFULIqJ_j5FZWqw00Vr30U',
    appId: '1:593099494761:android:bb27fda7ef5a27d56d19f8',
    messagingSenderId: '593099494761',
    projectId: 'emir-s-firebase-example',
    storageBucket: 'emir-s-firebase-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAUdt0Do_KReazbj6q1-yS1HAEeoYqUXU',
    appId: '1:593099494761:ios:20a48cbc5d5086ef6d19f8',
    messagingSenderId: '593099494761',
    projectId: 'emir-s-firebase-example',
    storageBucket: 'emir-s-firebase-example.appspot.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAUdt0Do_KReazbj6q1-yS1HAEeoYqUXU',
    appId: '1:593099494761:ios:c2e9f7e1e77369276d19f8',
    messagingSenderId: '593099494761',
    projectId: 'emir-s-firebase-example',
    storageBucket: 'emir-s-firebase-example.appspot.com',
    iosBundleId: 'com.example.firebaseExample.RunnerTests',
  );
}
